name: Code quality check
on: [workflow_dispatch, pull_request]
jobs:
  eslint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install yarn
        run: npm install --global yarn

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --cache-folder ~/.yarn

      - name: run eslint check
        run: yarn eslint . --max-warnings=0

  prettier_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: install yarn
        run: npm install --global yarn
      - name: install prettier
        run: yarn add prettier
      - name: Check prettier
        run: yarn prettier --check 'src/**/*.(ts|scss|js)'
